#pragma once
#define MAX_KEYBOARD_KEYS 350

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 800

#define BOARD_SCREEN_OFFSET_X 90
#define BOARD_SCREEN_OFFSET_Y 100

#define BOARDPIECE_WIDTH 100
#define BOARDPIECE_HEIGHT 100

#define BOARDPIECE_COUNT_X 11
#define BOARDPIECE_COUNT_Y 6

#define TILE_WIDTH 90
#define TILE_HEIGHT 90

#define CLICK_SPEED_X 5
#define CLICK_SPEED_Y 5
#define RECOIL_SPEED_X 2
#define RECOIL_SPEED_Y 2

#define CLICK_WIDTH 10
#define CLICK_HEIGHT 10

#define BOARDPIECE_TILE_INTERACTION_PRECISION 10


