#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 800

#define TILE_WIDTH 90
#define TILE_HEIGHT 90

#define BOARDPIECE_WIDTH 100
#define BOARDPIECE_HEIGHT 100

#define BOARDPIECE_COUNT_X 11
#define BOARDPIECE_COUNT_Y 6

#define BOARD_SCREEN_OFFSET_X 90
#define BOARD_SCREEN_OFFSET_Y 100

#define CLICK_WIDTH 10
#define CLICK_HEIGHT 10

#define MAX_KEYBOARD_KEYS 350

