enum struct INTERACTION_FLAG : __uint8_t{
    NONE = 0b0,
    DESTROY_TILE1 = 0b1,
    DESTORY_TILE2 = 0b01
};

INTERACTION_FLAG operator|(INTERACTION_FLAG lhs, INTERACTION_FLAG rhs);

INTERACTION_FLAG operator&(INTERACTION_FLAG lhs, INTERACTION_FLAG rhs);